### ISSUE TITLE
Proposal: implementation

### ISSUE THREAD

**Issue by Sispheor** [kalliope-project/kalliope_neuron_answer_of_everything#1]
```yml
- name: "test"
  signals:
    - order: "search on the internet {{ search }}"
  neurons:
    - answer_of_everything:
        engine: "wolfram"
        engine_parameters:  # optional
          parameter_name1: "value1"
          parameter_name2: "value2"
        search: "{{ search }}"
        say_template: "{{ answer_of_everything_response }}"
```
